### ISSUE TITLE
Inconsistent namespaces

### ISSUE THREAD

**Issue by daniel-rck** [GISLab-ELTE/aegis-origin#14]
Hello, I found some inconsistent namespaces.

Some were `ELTE.AEGIS.xyz` (e.g. https://github.com/GISLab-ELTE/aegis-origin/blob/master/AEGIS.Core/BasicPolygon.cs#L20), some where `AEGIS.xyz` (e.g. https://github.com/GISLab-ELTE/aegis-origin/blob/master/AEGIS.Tests.Core.Reference/Operations/CoordinateProjectionFactoryTest.cs#L23).

Should that be unified in some way?

**Comment by mcserep** [comment]
Hi!
Only the `AEGIS.Tests.Core.Reference` project contained some inconsistent namespaces, good eye on noticing them! 😀 
Thanks, I have fixed them in 5f88f72801e74a30b2648f86f07e61b546cd7b67.
