### ISSUE TITLE
netcoreapp3.1 out of support

### ISSUE THREAD

**Issue by daniel-rck** [GISLab-ELTE/aegis-origin#15]
Hi,
since December 13, 2022 `netcoreapp3.1` ist out of support. This version is used in all test projects. So the SDK version should be changed to .NET 6 (LTS) or 7 (STS).

I would make a PR, if I know wheater 6 or 7 should be targeted.

**Comment by mcserep** [comment]
Hi @daniel-rck,
Thanks for noting this, I have updated the test project to .NET 6 LTS in c166d670d7970d0d8f1a627422124ddab94ec410.
The library part of the project uses .NET Standard 2.0, so no upgrade was required there.
